name: Azure Web App Deploy
on:
push:
branches:
- main
jobs:
build-and-deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout code
4. Push Your Code to GitHub
4.1 Push Code to GitHub
Commit and push your changes to the main branch:
5. Monitor GitHub Actions
5.1 Monitor the Workflow
1. Go to the Actions tab of your GitHub repository.
2. Ensure the workflow runs successfully and deploys your application to Azure.
6. Access Your Deployed Application
6.1 Open Your Application
Once the deployment is successful, your application will be available at:
uses: actions/checkout@v2
- name: Set up Python
uses: actions/setup-python@v2
with:
python-version: '3.8'
- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install -r requirements.txt
- name: Create ZIP package
run: |
zip -r source_code.zip .
- name: Deploy to Azure Web App
uses: azure/webapps-deploy@v2
with:
app-name: 'myWebApp'
package: './source_code.zip'
publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
